version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: "celery_app"
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    command: celery -A app.tasks.celery_app worker --loglevel=info


  beat:
    build: .
    container_name: "celery_beat"
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    command: celery -A app.tasks.celery_app beat --loglevel=info
